"""Added Notification Model

Revision ID: 91353bc1a692
Revises: cc3c57c90697
Create Date: 2026-08-04 18:19:25.160337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91353bc1a692'
down_revision = 'cc3c57c90697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###
